name: formatter

on:
  workflow_dispatch:
  push:
    paths:
      - "src/**"
      - "include/**"
      - "examples/**"

jobs:
  run-ubuntu:
    name: Build sora-cpp-sdk for android_x86_64
    runs-on: ubuntu-24.04
    outputs:
      diff: ${{ steps.diff.outputs.diff }}
    env:
      TEST_SIGNALING_URL: ${{ secrets.TEST_SIGNALING_URL }}
      TEST_CHANNEL_ID_PREFIX: ${{ secrets.TEST_CHANNEL_ID_PREFIX }}
      TEST_SECRET_KEY: ${{ secrets.TEST_SECRET_KEY }}
      TEST_MATRIX_NAME: android_x86_64
    steps:
      - uses: actions/checkout@v6
      - name: Get versions from DEPS
        id: version
        run: |
          source DEPS
          echo "apt_install_llvm_version=$APT_INSTALL_LLVM_VERSION" >> $GITHUB_OUTPUT
      - name: Install clang tools
        run: |
          sudo apt-get update
          wget https://apt.llvm.org/llvm.sh
          chmod a+x llvm.sh
          sudo ./llvm.sh ${{ steps.version.outputs.apt_install_llvm_version }}
          sudo apt-get install -y clang-format-${{ steps.version.outputs.apt_install_llvm_version }}
      - name: Install deps for ubuntu-24.04_x86_64
        run: |
          sudo apt-get install -y software-properties-common

          # X11
          sudo apt-get install libx11-dev libxext-dev

          # OpenGL
          sudo apt-get install -y libgl-dev
      - name: Cache Dependencies
        uses: actions/cache@v5
        with:
          path: _install/android_x86_64/release
          key: android_x86_64-${{ hashFiles('VERSION', 'DEPS') }}
          restore-keys: |
            android_x86_64-
      - name: Cache Dependencies
        uses: actions/cache@v5
        with:
          path: _build/ubuntu-24.04_x86_64/release/clang-include-cleaner.json
          key: ubuntu-24.04_x86_64-${{ hashFiles('VERSION', 'DEPS') }}
          restore-keys: |
            ubuntu-24.04_x86_64-

      - run: python3 run.py build --disable-cuda --test android_x86_64
      - run: python3 run.py build --disable-cuda --test ubuntu-24.04_x86_64
      - name: Run IWYU and Clang Format
        id: diff
        run: |
          set +e

          python3 run.py iwyu ubuntu-24.04_x86_64
          if [ $? -ne 0 ]; then
            HAS_ERROR=true
            echo "iwyu has error"
          fi

          python3 run.py format
          if [ $? -ne 0 ]; then
            HAS_ERROR=true
            echo "clang format has error"
          fi

          echo "diff<<EOF" >> $GITHUB_OUTPUT
          git diff >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

          git diff --exit-code
          if [ $? -ne 0 ]; then
            HAS_ERROR=true
            echo "git diff has error"
          fi

          if [ "$HAS_ERROR" = "true" ]; then
            echo "Please fix them before commit."
            exit 1
          fi

  notification:
    name: Slack Notification
    runs-on: ubuntu-24.04
    needs:
      - run-ubuntu
    if: always()
    steps:
      - uses: rtCamp/action-slack-notify@v2
        if: |
          needs.run-ubuntu.result == 'failure'
        env:
          SLACK_CHANNEL: sora-cpp-sdk
          SLACK_COLOR: danger
          SLACK_TITLE: フォーマット失敗
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: |
            ```
            ${{ needs.run-ubuntu.outputs.diff }}
            ```
