name: formatter

on:
  push:
    paths-ignore:
      - "doc/**"
      - "**.md"
      - "LICENSE"
      - "NOTICE"

jobs:
  run-ubuntu:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - name: ubuntu-24.04_x86_64
            runs-on: ubuntu-24.04
            os: ubuntu
            arch: x86_64
    name: Build sora-cpp-sdk for ${{ matrix.platform.name }}
    runs-on: ${{ matrix.platform.runs-on }}
    outputs:
      diff: ${{ steps.diff.outputs.diff }}
    env:
      TEST_SIGNALING_URL: ${{ secrets.TEST_SIGNALING_URL }}
      TEST_CHANNEL_ID_PREFIX: ${{ secrets.TEST_CHANNEL_ID_PREFIX }}
      TEST_SECRET_KEY: ${{ secrets.TEST_SECRET_KEY }}
      TEST_MATRIX_NAME: ${{ matrix.platform.name }}
    steps:
      - uses: actions/checkout@v4
      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: _install/${{ matrix.platform.name }}/release
          key: ${{ matrix.platform.name }}-${{ hashFiles('VERSION') }}
      - name: Install deps for ${{ matrix.platform.name }}
        if: matrix.platform.os == 'ubuntu' && matrix.platform.arch == 'x86_64'
        run: |
          source VERSION
          sudo apt-get update
          sudo apt-get install -y software-properties-common

          # X11
          sudo apt-get install libx11-dev libxext-dev

          # OpenGL
          sudo apt-get install -y libgl-dev

          # clang-20
          wget https://apt.llvm.org/llvm.sh
          chmod a+x llvm.sh
          sudo ./llvm.sh 20
      - run: python3 run.py build --disable-cuda --test ${{ matrix.platform.name }}
      - name: Build Examples
        run: |
          cd examples
          mkdir examples_${{ matrix.platform.name }}
          for app in sdl_sample sumomo messaging_recvonly_sample; do
            python3 $app/${{ matrix.platform.name }}/run.py \
              --local-sora-cpp-sdk-dir .. \
              --local-sora-cpp-sdk-args=--disable-cuda \
              --install-dir `pwd`/../_install/ubuntu-24.04_x86_64/release
          done
        if: matrix.platform.os == 'ubuntu' && matrix.platform.name != 'ubuntu-22.04_armv8'
      - name: Run IWYU and Clang Format
        run: |
          set +e

          python3 run.py iwyu ubuntu-24.04_x86_64
          if [ $? -ne 0 ]; then
            HAS_ERROR=true
            echo "iwyu has error"
          fi

          python3 run.py format
          if [ $? -ne 0 ]; then
            HAS_ERROR=true
            echo "clang format has error"
          fi

          echo "diff<<EOF" >> $GITHUB_OUTPUT
          git diff >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

          git diff --exit-code
          if [ $? -ne 0 ]; then
            HAS_ERROR=true
            echo "git diff has error"
          fi

          if [ "$HAS_ERROR" = "true" ]; then
            echo "Please fix them before commit."
            exit 1
          fi

  notification:
    name: Slack Notification
    runs-on: ubuntu-24.04
    needs:
      - run-ubuntu
    if: always()
    steps:
      - uses: rtCamp/action-slack-notify@v2
        if: |
          needs.run-ubuntu.result == 'failure'
        env:
          SLACK_CHANNEL: sora-cpp-sdk
          SLACK_COLOR: danger
          SLACK_TITLE: フォーマット失敗
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: |
            ```
            ${{ needs.run-ubuntu.outputs.diff }}
            ```